apiVersion: cpo.opensource.cybertec.at/v1
kind: postgresql
metadata:
  name: cluster-1
spec:
 dockerImage: 'docker.io/cybertecpostgresql/cybertec-pg-container:postgres-rocky9-16.0-1-1'
  numberOfInstances: 1
  postgresql:
    version: '16'
  resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
    teamId: acid
    volume:
      size: 5Gi
  backup:
      pgbackrest:
        configuration:
          secret: cluster-1-s3-credentials
        global:
          repo1-path: /YOUR_PATH_INSIDE_THE_BUCKET/repo1/
          repo1-retention-full: '7'
          repo1-retention-full-type: count
        image: >-
          docker.io/cybertecpostgresql/cybertec-pg-container:pgbackrest-rocky9-16-13-1
        repos:
          - endpoint: YOUR_S3_ENDPOINT
            name: repo1
            region: YOUR_S3_REGION
            resource: YOUR_BUCKET_NAME
            schedule:
              full: 30 2 * * *
            storage: s3