apiVersion: cpo.opensource.cybertec.at/v1
kind: postgresql
metadata:
  name: ha-cluster-1
spec:
  dockerImage: 'docker.io/cybertecpostgresql/cybertec-pg-container:postgres-16.1-3-dev'
  numberOfInstances: 2
  postgresql:
    version: '16'
    parameters:
      password_encryption: "scram-sha-256"
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 100Mi
  teamId: acid
  volume:
    size: 5Gi

