---

# singleNamespace controls where CPO watches for PostgresClusters. When false,
# CPO watches for and responds to PostgresClusters in all namespaces. When true,
# CPO watches only the namespace in which it is installed.
singleNamespace: false

# debug allows you to enable or disable the "debug" level of logging.
debug: true

# imagePullSecretNames is a list of secret names to use for pulling controller images.
# More info: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecretNames: []


# Define the operator settings to add to the configmap
operatorSettings:
  operatorImage: 'docker.io/cybertecpostgresql/cybertec-pg-operator:0.5.0-2'
  namespace: '*'
  enable_pod_antiaffinity: 'true'
  operator_namespace: 'zalando'


