---

# singleNamespace controls where CPO watches for PostgresClusters. When false,
# CPO watches for and responds to PostgresClusters in all namespaces. When true,
# CPO watches only the namespace in which it is installed.
singleNamespace: false

# debug allows you to enable or disable the "debug" level of logging.
debug: true

# imagePullSecretNames is a list of secret names to use for pulling controller images.
# More info: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecretNames: []
  # - name: my-pull-secret

# Define the operator settings to add to the configmap
operatorSettings:
  operatorImage: 'docker.io/cybertecpostgresql/cybertec-pg-operator:v0.9.0-1'
  postgresImage: 'containers.cybertec.at/cybertec-pg-container/postgres:rocky9-18.1-2'
  poolerImage: 'containers.cybertec.at/cybertec-pg-container/pgbouncer:rocky9-1.25.0-2'
  watched_namespace: '*'
  enable_pod_antiaffinity: 'true'


