apiVersion: v2
name: postgres-cluster
description: Deploys a PostgreSQL cluster using the PostgreSQL operator

type: application
version: 18.6-1

appVersion: "18.6-1"

maintainers:
  - name: CYBERTEC PostgreSQL International GmbH
    email: info@cybertec.at

sources:
  - https://github.com/cybertec-postgresql/cybertec-pg-operator
