apiVersion: cpo.opensource.cybertec.at/v1
kind: postgresql
metadata:
  name: cluster-1-clone
spec:
  dockerImage: 'docker.io/cybertecpostgresql/cybertec-pg-container:postgres-17.2-4'
  numberOfInstances: 1
  postgresql:
    version: '17'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  teamId: acid
  volume:
    size: 5Gi
  backup:
    pgbackrest:
      configuration:
        secret: cluster-1-s3-credentials
      global:
        repo1-path: /YOUR_PATH_INSIDE_THE_BUCKET/repo1/
        repo1-retention-full: '7'
        repo1-retention-full-type: count
      image: 'docker.io/cybertecpostgresql/cybertec-pg-container:pgbackrest-17.2-4'
      repos:
        - endpoint: YOUR_S3_ENDPOINT
          name: repo1
          region: YOUR_S3_REGION
          resource: YOUR_BUCKET_NAME
          schedule:
            full: 30 2 * * *
          storage: s3
  clone:
    cluster: cluster-1 # A random cluster name can be used if the source cluster is not present on the k8s.
    pgbackrest:
      configuration:
        secret: cluster-1-s3-credentials
      options:
        repo1-path: /YOUR_PATH_INSIDE_THE_BUCKET_TO_THE_SOURCE_STANZA/repo1/
      repo:
        endpoint: YOUR_SOURCE_S3_ENDPOINT
        name: repo1
        region: YOUR_SOURCE_S3_REGION
        resource: YOUR_SOURCE_BUCKET_NAME
        storage: s3