apiVersion: cpo.opensource.cybertec.at/v1
kind: postgresql
metadata:
  name: ha-cluster-1
spec:
  dockerImage: 'docker.io/cybertecpostgresql/cybertec-pg-container:postgres-16.3-1'
  numberOfInstances: 1
  postgresql:
    version: '16'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  connectionPooler:
    dockerImage: 'docker.io/cybertecpostgresql/cybertec-pg-container:pgbouncer-1.22-1'
    mode: transaction
    numberOfInstances: 2
    resources:
      limits:
        cpu: '1'
        memory: 100Mi
      requests:
        cpu: 500m
        memory: 100Mi
    schema: pooler
    user: pooler
  teamId: acid
  volume:
    size: 5Gi

