{
 "title": "9_Alerting",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity_num=\"100\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low Alert",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity_num=\"200\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Medium Alert",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity_num=\"300\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{alertstate=\"firing\",severity_num=\"400\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution alert types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (severity,severity_num) (ALERTS)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Monitored Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (clusterid) (pg_up))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Monitored Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(count by (pod) (pg_up))", "legendFormat": "__auto" }
   ]
  },
  { "title": "Firing Alerts", "type": "alertlist", "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 } },
  { "title": "Pending Alerts", "type": "alertlist", "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 } }
 ]
}