{
 "title": "6_Backups",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(clusterid)" } }
  ]
 },
 "panels": [
  {
   "title": "Last Backup for",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpo_pgbackrest_time_since_last_backup_time_since_last_backup_completion{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wal-Archiver",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "avg(idelta(pg_stat_archiver_archived_count{clusterid=\"[[cluster]]\", role=\"master\"}[1m])) without (instance,ip)",
     "legendFormat": "Successfull Archiver"
    },
    {
     "expr": "avg(idelta(pg_stat_archiver_failed_count{clusterid=\"[[cluster]]\", role=\"master\"}[1m])) without (instance,ip)",
     "legendFormat": "Failed Archiver"
    }
   ]
  },
  {
   "title": "Backup-Duration",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "last_over_time(cpo_pgbackrest_duration_backup_duration{clusterid=\"[[cluster]]\",role=\"master\"}[15s])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Backups",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cpo_pgbackrest_list_backup_size{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpo_pgbackrest_list_backup_repo_size{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "last complete Backup",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "last_over_time(cpo_pgbackrest_time_since_backup_last_check{clusterid=\"[[cluster]]\",role=\"master\"}[15s])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}