{
 "title": "2_Cluster-Members",
 "time": { "from": "now-15s", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(clusterid)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({clusterid=\"[[cluster]]\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$pod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "pod" },
  {
   "title": "Pod-Role",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(pg_up{clusterid=\"[[cluster]]\",pod=\"$pod\"}[15s] ) OR on() vector(0) ",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "State",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(pg_up{clusterid=\"[[cluster]]\",pod=\"$pod\"}[15s] ) OR on() vector(0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Connections",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{clusterid=\"[[cluster]]\",pod=\"$pod\"})*100 /sum(pg_settings_max_connections{clusterid=\"[[cluster]]\",pod=\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Online time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((time()-process_start_time_seconds{clusterid=\"[[cluster]]\",pod=\"$pod\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff{clusterid=\"[[cluster]]\",application_name=\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((idelta(cpo_pgnodemx_cpuacct_usage{clusterid=\"[[cluster]]\",pod=\"$pod\"}[30s])/1000000000)/idelta(cpo_pgnodemx_cpuacct_usage_ts{clusterid=\"[[cluster]]\",pod=\"$pod\"}[30s])*100) without(instance,ip,role)/avg((cpo_pgnodemx_cpucfs_quota_us{clusterid=\"[[cluster]]\",pod=\"$pod\"}*100/cpo_pgnodemx_cpucfs_period_us{clusterid=\"[[cluster]]\",pod=\"$pod\"})) without (instance,ip,role)",
     "legendFormat": "% Usage"
    },
    { "legendFormat": "Limit" }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cpo_pgnodemx_mem_usage_in_bytes{clusterid=\"[[cluster]]\",pod=\"$pod\"})/(avg(cpo_pgnodemx_mem_limit{clusterid=\"[[cluster]]\",pod=\"$pod\"}))",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}