{
 "title": "3_Cluster-Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(clusterid)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({clusterid=\"[[cluster]]\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Count(ALERTS{clusterid=\"[[cluster]]\",alertstate='firing'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster-Type",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_settings_hot_standby{clusterid=\"[[cluster]]\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_settings_server_version_num{clusterid=\"[[cluster]]\",role=\"master\"})"
    }
   ]
  },
  {
   "title": "Used Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{clusterid=\"[[cluster]]\",role=\"master\",state=\"active\"})*100 /sum(pg_settings_max_connections{clusterid=\"[[cluster]]\",role=\"master\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache-Hit-Ratio",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{clusterid=\"[[cluster]]\",role=\"master\"})*100/sum(pg_stat_database_blks_hit{clusterid=\"[[cluster]]\",role=\"master\"}+pg_stat_database_blks_read{clusterid=\"[[cluster]]\",role=\"master\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Idle in Transactions",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{clusterid=\"[[cluster]]\",role=\"master\",state=\"idle in transaction\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "database size",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "sum(pg_database_size_bytes{clusterid=\"[[cluster]]\",role=\"master\"})/(1024*1024)",
     "legendFormat": "Total : [[pod]]"
    },
    {
     "expr": "pg_database_size_bytes{clusterid=\"[[cluster]]\",role=\"master\"}/(1024*1024)",
     "legendFormat": "{{datname}} -  ({{pod}})"
    }
   ]
  },
  {
   "title": "Locks - [[pod]]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (mode) (pg_locks_count{clusterid=\"[[cluster]]\",role=\"master\",mode=\"accessexclusivelock\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{clusterid=\"[[cluster]]\",role=\"master\",mode=\"exclusivelock\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{clusterid=\"[[cluster]]\",role=\"master\",mode=\"rowexclusivelock\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{clusterid=\"[[cluster]]\",role=\"master\",mode=\"sharerowexclusivelock\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{clusterid=\"[[cluster]]\",role=\"master\",mode=\"shareupdateexclusivelock\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (mode) (pg_locks_count{clusterid=\"[[cluster]]\",role=\"master\",mode=\"accesssharelock\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(pg_settings_max_connections{clusterid=\"[[cluster]]\",role=\"master\"})",
     "legendFormat": "Max Connections"
    },
    {
     "expr": "sum(pg_stat_activity_count{clusterid=\"[[cluster]]\",role=\"master\",state=\"active\"})",
     "legendFormat": "Connection Active"
    },
    {
     "expr": "count(cpo_pg_connections_backend_start{clusterid=\"[[cluster]]\",role=\"master\",state=\"idle\"})",
     "legendFormat": "Connection Idle"
    },
    {
     "expr": "count(cpo_pg_connections_backend_start{clusterid=\"[[cluster]]\",role=\"master\",state=\"idle in transaction\"})",
     "legendFormat": "Connection Idle in Transaction"
    },
    {
     "expr": "count(cpo_pg_connections_backend_start{clusterid=\"[[cluster]]\",role=\"master\",state=\"idle in transaction (aborted)\"})",
     "legendFormat": "Connection Idle in Transaction (aborted)"
    },
    {
     "expr": "count(cpo_pg_connections_backend_start{clusterid=\"[[cluster]]\",role=\"master\",state=\"fastpath function call\"})",
     "legendFormat": "Connection fastpath"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff{clusterid=\"[[cluster]]\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}