{
 "title": "8_Parameters",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(clusterid)" } }
  ]
 },
 "panels": [
  { "title": "Short Overview", "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Max-Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_connections{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shared-Buffer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_shared_buffers_bytes{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work-Mem",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_work_mem_bytes{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workers and Senders", "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Max Parallel Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Parallel Workers per Gather",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_workers_per_gather{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Parallel Maintenance Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_parallel_maintenance_workers{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Wal Senders",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_max_wal_senders{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Autovacuum", "type": "stat", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }, "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } } },
  {
   "title": "Global Autovaccum Max Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_autovacuum_max_workers{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Autovaccum Analyze Scale Factor",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_autovacuum_analyze_scale_factor{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Auitovaccum Analyze Threshold",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pg_settings_autovacuum_analyze_threshold{clusterid=\"[[cluster]]\",role=\"master\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}