{
 "title": "5_Pod-Informations",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(clusterid)" } },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values({clusterid=\"[[cluster]]\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod-Role",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_up{clusterid=\"[[cluster]]\",pod=~\"[[pod]]\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "Online time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((time()-process_start_time_seconds{clusterid=\"[[cluster]]\",pod=~\"[[pod]]\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((idelta(cpo_pgnodemx_cpuacct_usage{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}[30s])/1000000000)/idelta(cpo_pgnodemx_cpuacct_usage_ts{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}[30s])*100) without(instance,ip,role)/avg((cpo_pgnodemx_cpucfs_quota_us{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}*100/cpo_pgnodemx_cpucfs_period_us{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"})) without (instance,ip,role)",
     "legendFormat": "% Usage"
    },
    { "legendFormat": "Limit" }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cpo_pgnodemx_mem_usage_in_bytes{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"})/(avg(cpo_pgnodemx_mem_limit{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}))",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Storage-Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((cpo_pgnodemx_data_disk_total_bytes{clusterid=\"[[cluster]]\",pod=~\"[[pod]]\"}-cpo_pgnodemx_data_disk_available_bytes{clusterid=\"[[cluster]]\",pod=~\"[[pod]]\"})/cpo_pgnodemx_data_disk_total_bytes{clusterid=\"[[cluster]]\",pod=~\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg((idelta(cpo_pgnodemx_cpuacct_usage{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}[30s])/1000000000)/idelta(cpo_pgnodemx_cpuacct_usage_ts{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}[30s])*100) without(instance,ip,role)/100",
     "legendFormat": "% Usage"
    },
    {
     "expr": "avg((cpo_pgnodemx_cpucfs_quota_us{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}*100/cpo_pgnodemx_cpucfs_period_us{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"})) without (instance,ip,role)/100",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "CPU-Throttle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "avg((idelta(cpo_pgnodemx_cpustat_throttled_time{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}[30s])/1000000000)/idelta(cpo_pgnodemx_cpustat_snap_ts{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}[30s])*100) without (instance,ip,role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage-Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg((cpo_pgnodemx_data_disk_total_bytes{clusterid=\"[[cluster]]\",pod=~\"[[pod]]\"}-cpo_pgnodemx_data_disk_available_bytes{clusterid=\"[[cluster]]\",pod=~\"[[pod]]\"})/cpo_pgnodemx_data_disk_total_bytes{clusterid=\"[[cluster]]\",pod=~\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(rate(cpo_pgnodemx_disk_activities_sectors_read{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}[1m])*512) without(instance,ip,role)",
     "legendFormat": "{{mount_point}} - Reads"
    },
    {
     "expr": "avg(rate(cpo_pgnodemx_disk_activities_sectors_written{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}[1m])*512) without(instance,ip,role)",
     "legendFormat": "{{mount_point}} - Writes "
    }
   ]
  },
  {
   "title": "Memory Breakdown",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(cpo_pgnodemx_mem_cache{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "Cached"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_dirty{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "Dirty"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_shmem{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "shared mem"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_rss{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "RSS"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_mapped_file{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "Mapped file"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_kmem_usage_in_bytes{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "kmem"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_inactive_anon{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "Inactive anon"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_active_file{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "Active file"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_inactive_file{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "Inactive file"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(cpo_pgnodemx_mem_limit{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "Limit"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_request{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "Request"
    },
    {
     "expr": "avg(cpo_pgnodemx_mem_usage_in_bytes{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}) without (instance,ip,role)",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(clamp_min((cpo_pgnodemx_mem_limit{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"} - cpo_pgnodemx_mem_usage_in_bytes{clusterid=\"[[cluster]]\",pod=\"[[pod]]\"}),0)) without (instance,ip,role)",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_replication_pg_wal_lsn_diff{clusterid=\"[[cluster]]\",application_name=~\"[[pod]]\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}