{
 "title": "7_Query-Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(clusterid)" } },
   {
    "name": "datname",
    "label": "datname",
    "query": {
     "query": "label_values(pg_database_size_bytes{clusterid=\"[[cluster]]\"},datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top Statements mean_exec_time",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cpo_pg_statistics_statements_mean_mean_exec_time{clusterid=\"[[cluster]]\", role=\"master\",datname=~\"[[datname]]\"}[$__range])) without(instance, ip, deployment,pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Statements by blocks_read",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(avg_over_time(cpo_pg_statistics_statements_write_blks_read{clusterid=\"[[cluster]]\", role=\"master\",datname=~\"[[datname]]\"}[$__range])) without(instance, ip, deployment,pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Statements by total_exec_time",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(cpo_pg_statistics_statements_total_total_exec_time{clusterid=\"[[cluster]]\", role=\"master\",datname=~\"[[datname]]\"}[$__range])) without(instance, ip, deployment,pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}