apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-operator
  labels:
    application: postgres-operator
spec:
  replicas: 1
  strategy:
    type: "Recreate"
  selector:
    matchLabels:
      name: postgres-operator
  template:
    metadata:
      labels:
        name: postgres-operator
        cpo.cybertec.at/pod-type: postgres-operator
    spec:
      serviceAccountName: cpo-operator
      {{- with .Values.imagePullSecretNames }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: postgres-operator
        image: {{ .Values.operatorSettings.operatorImage }}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 250Mi
          limits:
            cpu: 500m
            memory: 500Mi
        securityContext:
          #runAsUser: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
        env:
        - name: POSTGRES_OPERATOR_CONFIGURATION_OBJECT
          value: postgresql-operator-configuration
        {{- if .Values.operatorSettings.enableJsonLogging }}
        - name: ENABLE_JSON_LOGGING
          value: "true"
        {{- end }}
