apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: cluster-1
spec:
  dockerImage: 'docker.io/cybertecpostgresql/cybertec-pg-container:postgres-15.2-5'
  numberOfInstances: 1
  postgresql:
    version: '15'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  teamId: acid
  volume:
    size: 5Gi
  users:
    applikationsuser:
      - login
    #storageClass: default-provisioner
