apiVersion: cpo.opensource.cybertec.at/v1
kind: postgresql
metadata:
  name: cluster-1
spec:
  dockerImage: 'containers.cybertec.at/cybertec-pg-container/postgres:rocky9-18.3-2'
  numberOfInstances: 1
  postgresql:
    version: '18'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  teamId: acid
  volume:
    size: 5Gi
    #storageClass: default-provisioner
  preparedDatabases:
    appl_db:
      defaultUsers: true
      extensions:
        dblink: public
      schemas:
        data: {}
        history:
          defaultRoles: true
          defaultUsers: false
