apiVersion: cpo.opensource.cybertec.at/v1
kind: postgresql
metadata:
  name: cluster-1
spec:
  dockerImage: 'containers.cybertec.at/cybertec-pg-container/postgres:rocky9-18.1-2'
  numberOfInstances: 1
  postgresql:
    version: '18'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  teamId: acid
  volume:
    size: 5Gi
    #storageClass: default-provisioner
  monitor:
    image: 'containers.cybertec.at/cybertec-pg-container/exporter:rocky9-18.1-2'
