apiVersion: cpo.opensource.cybertec.at/v1
kind: postgresql
metadata:
  name: standby-cluster-1
spec:
  standby:
    standby_host: "cluster-1.cpo"
    standby_port: "5432"
  dockerImage: 'docker.io/cybertecpostgresql/cybertec-pg-container:postgres-17.4-1'
  numberOfInstances: 1
  postgresql:
    version: '17'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  teamId: acid
  volume:
    size: 5Gi
    #storageClass: default-provisioner
