apiVersion: cpo.opensource.cybertec.at/v1
kind: postgresql
metadata:
  name: tde-cluster-1
spec:
  dockerImage: 'containers.cybertec.at/cybertec-pgee-container/postgres:rocky9-18.3-1'
  numberOfInstances: 1
  postgresql:
    version: '18'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  teamId: acid
  tde:
    enable: true
    keybits: 256
  volume:
    size: 5Gi
    #storageClass: default-provisioner
