apiVersion: cpo.opensource.cybertec.at/v1
kind: postgresql
metadata:
  name: beta-cluster-1
spec:
  dockerImage: 'docker.io/cybertecpostgresql/cybertec-pg-container:postgres-17beta2-1'
  numberOfInstances: 1
  postgresql:
    version: '17'
    parameters:
      shared_preload_libraries: 'pg_stat_statements'
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  teamId: acid
  volume:
    size: 5Gi
  backup:
    pgbackrest:
      configuration:
        secret: cluster-1-pvc-configuration
      global:
        repo1-retention-full: '3'
        repo1-retention-full-type: count
      image: docker.io/cybertecpostgresql/cybertec-pg-container:pgbackrest-17beta3-1'
      repos:
        - name: repo1
          schedule:
            full: 30 2 * * *
          storage: pvc
          volume:
            size: 10Gi